### ISSUE TITLE
Wrong supported principals

### ISSUE THREAD

**Issue by scalding** [Unicon/shib-mfa-duo-auth#1]
[https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/resources/META-INF/shibboleth-idp/conf/global.xml#L11-L25]

Distributed supported principals should be generic. Any local support and/or overrides should be added to `conf/global.xml`.

**Comment by langedb** [comment]
That one was my fault (bad PR awhile back), I'll send in a new PR to fix.
