### ISSUE TITLE
unchecked call to buildAuthenticationResult(ProfileRequestContext<InboundMessageType,OutboundMessageType> as a member of the raw type AbstractValidationAction Warnings at compile time

### ISSUE THREAD

**Issue by Ghilteras** [Unicon/shib-mfa-duo-auth#17]
Looks like this line generates warnings for unchecked calls to `buildAuthenticationResult` called as raw Type without `InboundMessageType` and `OutboundMessageType` type-parameters 

https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/authn/ValidateDuoResponse.groovy#L74

**Comment by mapgrady** [comment]
You'll want to note the Support Notice at the top of the README on the main page of this repo:

  https://github.com/Unicon/shib-mfa-duo-auth <https://github.com/Unicon/shib-mfa-duo-auth>

This code is no longer supported. One shouldn't be running a Shib IdP earlier than v3.3.x, and as of v3.3, native support for Duo was included in the Shib IdP, and this code would no longer work without changes. And there was no advantage of making those changes, and continuing to support this as an extension to the IdP.

> On Dec 21, 2018, at 12:58 PM, Angelo Pantano <notifications@github.com> wrote:
> 
> Looks like this line generates warnings for unchecked calls to buildAuthenticationResult called as raw Type without InboundMessageType and OutboundMessageType type-parameters
> 
> https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/authn/ValidateDuoResponse.groovy#L74 <https://github.com/Unicon/shib-mfa-duo-auth/blob/master/src/main/groovy/net/unicon/iam/shibboleth/idp/authn/duo/authn/ValidateDuoResponse.groovy#L74>
--
Michael A. Grady
IAM Architect, Unicon, Inc.
