### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/shib-mfa-duo-auth#5]
Update the readme with additional docs on what the module does, how it builds, how you configure it, etc.

**Comment by scalding** [comment]
Few things that might help with this:
1. add `duo.properties` file to the distribution
2. reorganize the distribution so that the layout matches the standard Shibboleth IdP filesystem layout
3. upload the distribution to some place convenient that can be referenced from the docs

**Comment by langedb** [comment]
Agree with 1 & 2. GitHub has the release area for 3.

**Comment by scalding** [comment]
so, we just add uploading to the release area for 3. We can add that as part of the build process, I believe.

**Comment by scalding** [comment]
Initial documentation has been handled by a pull request
