### ISSUE TITLE
Missing duo.properties

### ISSUE THREAD

**Issue by serac** [Unicon/shib-mfa-duo-auth#7]
The duo.properties file mentioned in the README is not included in the source tree. While astute deployers can probably figure out by reading source what properties are needed, its absence appears to be an oversight.

**Comment by scalding** [comment]
Thanks for the note. The file you are looking for can be found at `src/main/dist/conf/duo.properties`. For the gradle distribution plugin, anything in the `src/main/dist` directory is added to the distribution as is. Does that help?

**Comment by serac** [comment]
I see that in the source tree by browsing there directly. So much for GitHub search. It's not included in the dist tarball, which is where I was looking initially:

```
$ tar -tzvf shib-mfa-duo-auth-1.0.tar.gz | grep duo.properties
```

**Comment by serac** [comment]
I think this is a documentation problem at best. The docs suggest you can install using the release bundles available in GitHub, but that appears not to be the case. When I build the project from source I see everything I need, including duo.properties.

**Comment by scalding** [comment]
Thanks for this. What appears to be the problem is that the release files were uploaded a little early, and haven't been updated to reflect the new layout. As you found, it's probably best to use the source rather than the releases now.
